# Archivo: .streamlit/secrets.toml

[neon_db]
user = "neondb_owner"
password = "npg_4PjbrOL5gkNJ"
host = "ep-snowy-sound-adzrmc8e-pooler.c-2.us-east-1.aws.neon.tech" # Reemplaza con el host de tu endpoint
database = "neondb" # Generalmente 'neondb' o el que hayas creado
port = 5432
