[gsheets]
type = "service_account" 
project_id = "control-gasolina-473719"
private_key_id = "fabddf9547342887a8b54b061777711b60bd1a77"

# ¡CLAVE PRIVADA EN COMILLAS TRIPLES!
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDjuPxN2vQTdyqd
e0u/Rpqfd9aslTUSOEx2WrRW9OZnr8mLeTnAPByt8s1V9EfjK9jNHgdhpuzKA2QN
YXEqtvh+d5HOUssMqRS8zy3CI+OCiireTZ/2uSZXUT+Cgq29GPP7RXBsHWraanbB
WlxO6ZkrcxdDvOyM4G6t7ARtiWslZ7n47fhVL10Kzw12w8Uh5+CDRoGQLVElRq0M
FE9Bf7BXjqtLKhWdEB/vL+0qUaOFsD+T49cRmrYFqYuRhYagl4oRD4rE8M1Frgah
aiFKAUR0NojUEzA/sVPvBG2fxwIg8wcWqASQdVH2nPp4LmUUrmlPEkpr3FCiZNtq
WNOrIb8ZAgMBAAECggEALZ5jdtJHxnV/JTyrpDYH6C3I5NpgHxYFpUkO6wOU+40A
zk665bp1EVi8Tz2IQCdKv26GUobu1RpASxjr439zgNxBqog18oOVqqxDUarAWyiE
JXP9+V5GYsQdOa8lkGXlDH9w4cuz2eztfNb1+n375/8epDx+08rrCS7ohSv7+aow
uL9DNEpWLGVbJ95gbfd6CmpkfVTjNciRKZ3iIDphIWdOSFlYOm7BiLF18vWZyM+5
fEHfAgiYxQhHpLVHwYDAmetxJLPiw04+7p4Ml4vL6X/oloCfK7BLe6pGeBEzPssk
s0cQq+keOvjcEvyTWVPvmuLn8fTSlnm+crcBvS8QHQKBgQD/W6XdSqmXXy3H4bFU
jFIR86252THb30bMyWCPuWXrQclOf85pQwwJxMNpuf+snh3EsTdJ+hhWwGwJ/1GH
fNEiKula5fSjqPF1VnuOOKGeQhMiDU7YwP0t5ELMfoMWcaX4pu05c26odsKryl88
NHff23VXLPkvbKjg3UwN17jYLQKBgQDkS40VwDwV3baLXtMcP511zX5P1FI5S6Od
3LrwSsVOl7q7Vop0hmB+cEoiMqXsWPR2aSXrLqIdpLeSkJxMa1T/HKTIxWgIYcQY
L5btKXoPybbAEeDt2N5e6YUTshUfEfRXDs8Cm8ocB/ITcYKKcmDXeyi4AoH0Y9uo
GXWmae2KHQKBgDEZNQ4UggE56rqI+aixBkKvYNLgIQcOqjVL7wYTdrZCQuuWBWEV
5CWosI4OlkthZ4XfMStHLBDaFKvjbJCpfiicqZuxpVUmca7G/yC8YM7mE3mzp1pj
2QpO3k0lch0JowjpR6mJOVio5QtU8PTJfdcMAkbNvefRc7MwuaPbu43NAoGBAMBX
pxacUANcOWBTFCrIrjGCYNmBWYVMZR2ryxSI6pO84mbUEvL6BHKCyPLnGUR37f+V
t4zeTVgMX13s2MLJ62LFD1DYgT4OoNh/v/kw6NZEbOSGK6w4+6GbvbNKZuE2j1aJ
83+PIklbqGkZSZK7qzvhV/0wn6z4NSj7ylPbC3dBAoGAYxvDx6aaJzWzgLmI/5nf
JhGUMgTr21etl8sI/d4aKM8swQjitN+dYJcQ+5Lgw4DRS6NNh2SfwPL4pSEIlEqa
WjE+dE+x22g8vIeU4YngKUsv9etN6pDnbyUhPKJFq40SYlfeM4PVI2TVEhJYAB5C
xSeVfwW1Ctqoa5Q03nA/lEE=
-----END PRIVATE KEY-----
"""

client_email = "gasolina@control-gasolina-473719.iam.gserviceaccount.com"
client_id = "111838438288670738828"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/gasolina%40control-gasolina-473719.iam.gserviceaccount.com"
