[gsheets]
# 1. Copia el valor de la clave "type" de tu archivo JSON.
type = "service_account" 

# 2. Copia el valor de la clave "project_id" de tu archivo JSON.
project_id = "control-gasolina-473719"

# 3. Copia el valor de la clave "private_key_id" de tu archivo JSON.
private_key_id = "fabddf9547342887a8b54b061777711b60bd1a77"

# 4. Esta es la más importante. Copia el valor de la clave "private_key"
#    COMPLETO, incluyendo los saltos de línea (\n), y envuélvelo en comillas
#    TRIPLES (cuidado con no copiar espacios extra al final).
private_key = """-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDjuPxN2vQTdyqd\ne0u/Rpqfd9aslTUSOEx2WrRW9OZnr8mLeTnAPByt8s1V9EfjK9jNHgdhpuzKA2QN\nYXEqtvh+d5HOUssMqRS8zy3CI+OCiireTZ/2uSZXUT+Cgq29GPP7RXBsHWraanbB\nWlxO6ZkrcxdDvOyM4G6t7ARtiWslZ7n47fhVL10Kzw12w8Uh5+CDRoGQLVElRq0M\nFE9Bf7BXjqtLKhWdEB/vL+0qUaOFsD+T49cRmrYFqYuRhYagl4oRD4rE8M1Frgah\naiFKAUR0NojUEzA/sVPvBG2fxwIg8wcWqASQdVH2nPp4LmUUrmlPEkpr3FCiZNtq\nWNOrIb8ZAgMBAAECggEALZ5jdtJHxnV/JTyrpDYH6C3I5NpgHxYFpUkO6wOU+40A\nzk665bp1EVi8Tz2IQCdKv26GUobu1RpASxjr439zgNxBqog18oOVqqxDUarAWyiE\nJXP9+V5GYsQdOa8lkGXlDH9w4cuz2eztfNb1+n375/MepDx+08rrCS7ohSv7+aow\nuL9DNEpWLGVbJ95gbfd6CmpkfVTjNciRKZ3iIDphIWdOSFlYOm7BiLF18vWZyM+5\nfEHfAgiYxQhHpLVHwYDAmetxJLPiw04+7p4Ml4vL6X/oloCfK7BLe6pGeBEzPssk\ns0cQq+keOvjcEvyTWVPvmuLn8fTSlnm+crcBvS8QHQKBgQD/W6XdSqmXXy3H4bFU\njFIR86252THb30bMyWCPuWXrQclOf85pQwwJxMNpuf+snh3EsTdJ+hhWwGwJ/1GH\nfNEiKula5fSjqPF1VnuOOKGeQhMiDU7YwP0t5ELMfoMWcaX4pu05c26odsKryl88\nNHff23VXLPkvbKjg3UwN17jYLQKBgQDkS40VwDwV3baLXtMcP511zX5P1FI5S6Od\n3LrwSsVOl7q7Vop0hmB+cEoiMqXsWPR2aSXrLqIdpLeSkJxMa1T/HKTIxWgIYcQY\nL5btKXoPybbAEeDt2N5e6YUTshUfEfRXDs8Cm8ocB/ITcYKKcmDXeyi4AoH0Y9uo\nGXWmae2KHQKBgDEZNQ4UggE56rqI+aixBkKvYNLgIQcOqjVL7wYTdrZCQuuWBWEV\n5CWosI4OlkthZ4XfMStHLBDaFKvjbJCpfiicqZuxpVUmca7G/yC8YM7mE3mzp1pj\n2QpO3k0lch0JowjpR6mJOVio5QtU8PTJfdcMAkbNvefRc7MwuaPbu43NAoGBAMBX\npxacUANcOWBTFCrIrjGCYNmBWYVMZR2ryxSI6pO84mbUEvL6BHKCyPLnGUR37f+V\nt4zeTVgMX13s2MLJ62LFD1DYgT4OoNh/v/kw6NZEbOSGK6w4+6GbvbNKZuE2j1aJ\n83+PIklbqGkZSZK7qzvhV/0wn6z4NSj7ylPbC3dBAoGAYxvDx6aaJzWzgLmI/5nf\nJhGUMgTr21etl8sI/d4aKM8swQjitN+dYJcQ+5Lgw4DRS6NNh2SfwPL4pSEIlEqa\nWjE+dE+x22g8vIeU4YngKUsv9etN6pDnbyUhPKJFq40SYlfeM4PVI2TVEhJYAB5C\nxSeVfwW1Ctqoa5Q03nA/lEE=\n-----END PRIVATE KEY-----\n"""

# 5. Copia el valor de la clave "client_email" (es la cuenta que debe tener permisos de Editor).
client_email = "gasolina@control-gasolina-473719.iam.gserviceaccount.com"

# 6. Copia el valor de la clave "client_id".
client_id = "111838438288670738828"

# 7. Copia el valor de la clave "auth_uri".
auth_uri = "https://accounts.google.com/o/oauth2/auth"

# 8. Copia el valor de la clave "token_uri".
token_uri = "https://oauth2.googleapis.com/token"

# 9. Copia el valor de la clave "auth_provider_x509_cert_url".
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"

# 10. Copia el valor de la clave "client_x509_cert_url".
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/gasolina%40control-gasolina-473719.iam.gserviceaccount.com"
